### ISSUE TITLE
Test Compile Error

### ISSUE THREAD

**Issue by damianburrin** [ChrisEilbeck/TTGO-FSK-Beacon#6]
I'm getting an out of scope error when verifying the code.  

Board set to TBeam

![image](https://user-images.githubusercontent.com/18092613/195404696-80013811-3764-45ec-82a6-7bd33838d668.png)

**Comment by ChrisEilbeck** [comment]
See the updated README.md in the repo.  Note, this will not work on a T-Beam yet
